# -*- coding: utf-8 -*-
"""mini project ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-XOMhRBmllnL9-zSlzKuSmsh-q19hiI

# Step 1 – Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ====================================================
# TASK 1 — RESEARCH PAPER IDENTIFICATION
# ====================================================

print("\n========== RESEARCH PAPER ==========")

print("Research Paper Title:")
print("Customer Churn Prediction Using Machine Learning Techniques")

print("\nAim:")
print("To predict telecom customer churn using machine learning models.")

print("\nObjectives:")
print("1. Improve customer retention")
print("2. Compare ML algorithms")
print("3. Improve prediction accuracy")

print("\nMethodology:")
print("Data Collection -> Preprocessing -> Model Training -> Evaluation")

print("\nConclusion:")
print("Ensemble methods provide better churn prediction accuracy.")

"""# **Step 2 – Load Dataset**"""

data = pd.read_csv("Telco-Customer-Churn.csv")
print(data.head())

print("\n================ DATASET SHAPE ================")
print(data.shape)

print("\n================ DATASET INFO ================")
print(data.info())

print("\n================ MISSING VALUES ================")
print(data.isnull().sum())

"""# **Step 3 – Remove Unnecessary Column**"""

data.drop("customerID", axis=1, inplace=True)

"""# **Step 4 –  Convert Data Type**"""

data["TotalCharges"] = pd.to_numeric(
    data["TotalCharges"],
    errors="coerce"
)

"""# **Step 5 – Handle Missing Values**"""

data["TotalCharges"].fillna(
    data["TotalCharges"].median(),
    inplace=True
)

"""# **Step 6 – Label Encoding**"""

encoder = LabelEncoder()

for column in data.columns:
    if data[column].dtype == "object":
        data[column] = encoder.fit_transform(data[column])

"""# **Step 7 – Separate Input and Output**"""

X = data.drop("Churn", axis=1)
y = data["Churn"]

"""# **STEP 8 — Feature Scaling**"""

scaler = StandardScaler()
X = scaler.fit_transform(X)

"""# **Step 9 – Train Test Split**


"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""# **STEP 10 — Logistic Regression Model**"""

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

"""# **STEP 11 — Accuracy Calculation**

---


"""

lr_accuracy = accuracy_score(y_test, lr_pred)
print(f"Logistic Regression Accuracy: {lr_accuracy*100:.2f}%")

"""# **STEP 12 — Classification Report**

"""

print(classification_report(y_test, lr_pred))

"""# **STEP 13 — Confusion Matrix**"""

lr_cm = confusion_matrix(y_test, lr_pred)

"""# **STEP 14 — Heatmap Visualization**"""

plt.figure(figsize=(5,4))

sns.heatmap(
    lr_cm,
    annot=True,
    fmt='d'
)

plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""# **STEP 15 — Decision Tree**"""

dt_model = DecisionTreeClassifier(max_depth=5)

dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)
print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")

print("\nDecision Tree Classification Report")
print(classification_report(y_test, dt_pred))

dt_cm = confusion_matrix(y_test, dt_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    dt_cm,
    annot=True,
    fmt='d'
)

plt.title("Decision Tree Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""# **STEP 16 — Random Forest**"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")

print("\nRandom Forest Classification Report")
print(classification_report(y_test, rf_pred))

rf_cm = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    rf_cm,
    annot=True,
    fmt='d'
)

plt.title("Random Forest Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""# **STEP 17 — XGBoost**"""

xgb_model = XGBClassifier(
    eval_metric='logloss',
    use_label_encoder=False
)

xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
xgb_accuracy = accuracy_score(y_test, xgb_pred)
print(f"XGBoost Accuracy: {xgb_accuracy:.4f}")

print("\nXGBoost Classification Report")
print(classification_report(y_test, xgb_pred))

xgb_cm = confusion_matrix(y_test, xgb_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    xgb_cm,
    annot=True,
    fmt='d'
)

plt.title("XGBoost Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""# **STEP 18 — Model Comparison Table**"""

comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest", "XGBoost"],
    "Accuracy": [lr_accuracy, dt_accuracy, rf_accuracy, xgb_accuracy]
})
display(comparison)

"""# **STEP 19 — Accuracy Graph**"""

plt.figure(figsize=(10, 6))
plt.bar(
    comparison["Model"],
    comparison["Accuracy"],
    color=['skyblue', 'lightcoral', 'lightgreen', 'gold']
)
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.ylim(0.0, 1.0) # Set y-axis limit for accuracy
plt.show()

"""# **STEP 20 — Feature Importance**"""

importance = pd.DataFrame({

    "Feature": data.drop("Churn", axis=1).columns,
    "Importance": rf_model.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== FEATURE IMPORTANCE ==========")
print(importance)

plt.figure(figsize=(10,6))

sns.barplot(
    x="Importance",
    y="Feature",
    data=importance
)

plt.title("Feature Importance")

plt.show()

"""# **Step 21 -Customer Churn Status**"""

sample_prediction = xgb_model.predict(X_test[:10])

print("\nActual Values:")
print(y_test[:10].values)

print("\n========== CUSTOMER CHURN STATUS ==========")

for i in range(10):

    if sample_prediction[i] == 1:
        print(f"Customer {i+1} : Churn")

    else:
        print(f"Customer {i+1} : No Churn")

sample_prediction = xgb_model.predict(X_test[:10])

print(f"Predicted Values:\n{sample_prediction}")

print("\nActual Values:")
print(y_test[:10].values)

print("\n========== CUSTOMER CHURN STATUS ==========")

for i in range(10):

    if sample_prediction[i] == 1:
        print(f"Customer {i+1} : Churn")

    else:
        print(f"Customer {i+1} : No Churn")

"""# **Step 22 - Overfitting/Underfitting Analysis**"""

print("\n========== MODEL ANALYSIS ==========")

print("Logistic Regression : Slight underfitting")
print("Decision Tree       : May overfit")
print("Random Forest       : Better generalization")
print("XGBoost             : Best bias-variance balance")

"""# **STEP 23 — Final Result**"""

X_new = X_test[0:1]  # Using the first sample from X_test as an example for new data

pred = lr_model.predict(X_new)
prob = lr_model.predict_proba(X_new)

print(f"Churn: {pred[0]}")
print(f"Probability: {prob[0][1]:.2%}")

best_model = comparison.loc[
    comparison["Accuracy"].idxmax(),
    "Model"
]
best_accuracy = comparison["Accuracy"].max()
print(f"Best Model : {best_model}")
print(f"Best Accuracy : {best_accuracy:.2f}")

# ============================================================
# LIVE CUSTOMER CHURN PREDICTION SYSTEM
# ============================================================

while True:

    print("\n========== CUSTOMER CHURN CHECK ==========")

    # USER INPUT

    tenure = int(input("Enter Tenure (months): "))

    monthly_charges = float(input("Enter Monthly Charges: "))

    contract = int(input(
        "Contract Type (0=Month-to-month, 1=One year, 2=Two year): "
    ))

    # ========================================================
    # CREATE CUSTOMER DATA
    # ========================================================

    new_customer = [[

        1,                  # gender
        0,                  # SeniorCitizen
        1,                  # Partner
        0,                  # Dependents
        tenure,
        1,                  # PhoneService
        0,                  # MultipleLines
        2,                  # InternetService
        0,                  # OnlineSecurity
        1,                  # OnlineBackup
        0,                  # DeviceProtection
        0,                  # TechSupport
        1,                  # StreamingTV
        1,                  # StreamingMovies
        contract,
        1,                  # PaperlessBilling
        2,                  # PaymentMethod
        monthly_charges,
        monthly_charges * tenure

    ]]

    # ========================================================
    # APPLY SCALING
    # ========================================================

    new_customer_scaled = scaler.transform(new_customer)

    # ========================================================
    # PREDICT CHURN
    # ========================================================

    prediction = xgb_model.predict(new_customer_scaled)

    # ========================================================
    # SHOW RESULT
    # ========================================================

    print("\n========== RESULT ==========")

    if prediction[0] == 1:

        print("Customer Will Churn")

    else:

        print("Customer Will NOT Churn")

    # ========================================================
    # ASK USER TO CONTINUE
    # ========================================================

    choice = input("\nDo You Want To Check Another Customer? (yes/no): ")

    if choice.lower() == "no":

        print("\n========== SYSTEM CLOSED ==========")
        print("Thank You")

        break